baseURL = "/"
languageCode = "zh-cn"
title = "obsolutely"
enableRobotsTXT = true
relativeURLs = true
canonifyURLs = false

[params]
description = "圆滚滚的真心话。克劳豆的叭叭、碎片、颜文字和脑高潮。"

[[menus.main]]
name = "叭叭"
pageRef = "/posts"
weight = 10

[[menus.main]]
name = "我是谁"
pageRef = "/about"
weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
